insert into Place (id, name) values (1, 'La Paz');
insert into Place (id, name) values (2, 'Mamburao');
insert into Place (id, name) values (3, 'Sembungin');
insert into Place (id, name) values (4, 'Zyukayka');
insert into Place (id, name) values (5, 'Remedios');
insert into Place (id, name) values (6, 'Mingelchaur');
insert into Place (id, name) values (7, 'Chengjiang');
insert into Place (id, name) values (8, 'Bigaa');
insert into Place (id, name) values (9, 'Shanghu');
insert into Place (id, name) values (10, 'Ciherang');
insert into Place (id, name) values (11, 'San Juan');
insert into Place (id, name) values (12, 'Murygino');
insert into Place (id, name) values (13, 'Guayabal');
insert into Place (id, name) values (14, 'Kim Sơn');
insert into Place (id, name) values (15, 'Langkaplancar');
insert into Place (id, name) values (16, 'Pantenan');
insert into Place (id, name) values (17, 'Xigangzi');
insert into Place (id, name) values (18, 'Dongtou');
insert into Place (id, name) values (19, 'Mlandizi');
insert into Place (id, name) values (20, 'San Francisco');
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (1, 'Blogspan', '8', 8, 18, '2022-11-20', 681, 2, 'Zontrax', false, 4.64);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (2, 'Mydo', '037', 6, 18, '2022-12-04', 169, 2, 'Zathin', false, 1.44);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (3, 'Skipfire', '0', 20, 3, '2022-11-18', 142, 0, 'Aerified', true, 7.32);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (4, 'Edgepulse', '2', 5, 4, '2022-12-08', 339, 0, 'Tin', true, 5.72);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (5, 'Myworks', '93', 11, 20, '2022-12-06', 939, 1, 'Sonair', false, 10.21);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (6, 'Devcast', '8', 9, 1, '2022-11-30', 945, 2, 'Tin', false, 7.84);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (7, 'Kazio', '039', 14, 1, '2022-11-14', 729, 2, 'Lotstring', false, 0.51);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (8, 'Yata', '548', 6, 1, '2022-11-18', 649, 2, 'Tampflex', false, 13.39);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (9, 'Mydeo', '4', 1, 1, '2022-12-07', 855, 2, 'Flexidy', false, 13.95);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (10, 'Jatri', '67', 5, 4, '2022-12-09', 345, 0, 'Zathin', true, 11.89);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (11, 'Devbug', '02768', 15, 10, '2022-11-26', 569, 2, 'Zathin', false, 0.81);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (12, 'Blogtag', '6606', 7, 5, '2022-12-06', 822, 2, 'Latlux', true, 13.98);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (13, 'Twitterwire', '34', 8, 4, '2022-11-16', 93, 1, 'Prodder', true, 3.99);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (14, 'Roodel', '63', 6, 12, '2022-11-19', 455, 2, 'Mat Lam Tam', true, 1.9);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (15, 'Youbridge', '42', 16, 6, '2022-11-17', 148, 2, 'Tampflex', true, 8.65);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (16, 'Photobug', '74381', 8, 14, '2022-11-28', 299, 1, 'Regrant', true, 9.2);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (17, 'Quamba', '87', 6, 3, '2022-12-12', 352, 1, 'Voyatouch', false, 11.88);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (18, 'Omba', '6', 9, 2, '2022-11-23', 407, 2, 'Bamity', true, 8.24);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (19, 'Twiyo', '00576', 3, 12, '2022-11-12', 835, 0, 'Stringtough', true, 13.13);
insert into Flight (id, airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values (20, 'Yakijo', '54417', 20, 5, '2022-11-25', 748, 2, 'Fix San', true, 0.9);
