insert into Place (name) values ('Barcelona'); insert into Analytics default values;
insert into Place (name) values ('Madrid'); insert into Analytics default values;
insert into Place (name) values ('Bilbao'); insert into Analytics default values;
insert into Place (name) values ('Paris'); insert into Analytics default values;
insert into Place (name) values ('New York'); insert into Analytics default values;
insert into Place (name) values ('Los Angeles'); insert into Analytics default values;
insert into Place (name) values ('Roma'); insert into Analytics default values;
insert into Place (name) values ('Sevilla'); insert into Analytics default values;
insert into Place (name) values ('Milano'); insert into Analytics default values;
insert into Place (name) values ('Buenos Aires'); insert into Analytics default values;
insert into Place (name) values ('Medellin'); insert into Analytics default values;
insert into Place (name) values ('Caracas'); insert into Analytics default values;
insert into Place (name) values ('London'); insert into Analytics default values;
insert into Place (name) values ('Dublin'); insert into Analytics default values;
insert into Place (name) values ('Berlin'); insert into Analytics default values;
insert into Place (name) values ('Tokyo'); insert into Analytics default values;
insert into Place (name) values ('Beijing'); insert into Analytics default values;
insert into Place (name) values ('Amsterdam'); insert into Analytics default values;
insert into Place (name) values ('Prague'); insert into Analytics default values;
insert into Place (name) values ('San Francisco'); insert into Analytics default values;
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '1428', 8, 18, '2022-11-20', 681, 1, 'Barcelona', false, 4.64);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '4243', 8, 18, '2022-11-19', 760, 1, 'Barcelona', false, 8.54);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '3237', 6, 18, '2022-12-04', 169, 1, 'Zathin', false, 1.44);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '1232', 20, 3, '2022-11-18', 142, 0, '', true, 7.32);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '6432', 5, 4, '2022-12-08', 339, 0, '', true, 5.72);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '9433', 11, 20, '2022-12-06', 939, 1, 'Pakistan', false, 10.21);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Vueling', '5238', 9, 1, '2022-11-30', 945, 1, 'Lyon', false, 7.84);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Rayanair', '0239', 14, 1, '2022-11-14', 729, 1, 'Lotstring', false, 0.51);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Rayanair', '5468', 6, 1, '2022-11-18', 649, 1, 'Tampflex', false, 13.39);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Rayanair', '4792', 1, 2, '2022-12-07', 855, 1, 'Flexidy', false, 13.95);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Rayanair', '6577', 5, 4, '2022-12-09', 345, 0, '', true, 11.89);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Rayanair', '2468', 15, 10, '2022-11-26', 569, 1, 'Zathin', false, 0.81);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Emirates', '6606', 7, 5, '2022-12-06', 822, 0, '', true, 13.98);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Emirates', '3496', 8, 4, '2022-11-16', 93, 1, 'Prodder', true, 3.99);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Emirates', '6783', 6, 12, '2022-11-19', 455, 1, 'Mat Lam Tam', true, 1.9);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Emirates', '4234', 16, 6, '2022-11-17', 148, 0, '', true, 8.65);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Emirates', '7431', 8, 14, '2022-11-28', 299, 1, 'Regrant', true, 9.2);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Iberia', '8768', 6, 3, '2022-12-12', 352, 1, 'Voyatouch', false, 11.88);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Iberia', '6875', 9, 2, '2022-11-23', 407, 0, '', true, 8.24);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Iberia', '6576', 3, 12, '2022-11-12', 835, 0, '', true, 13.13);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Iberia', '4417', 20, 5, '2022-11-25', 748, 1, 'Madrid', true, 0.9);
insert into Flight (airline, flight_num, origin, destination, date, price, layover, layover_text, luggage, transit_time) values ('Iberia', '4132', 8, 18, '2022-11-21', 748, 1, 'Madrid', true, 0.9);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (9, 'Morna', 'Davidovsky', 'test@email.com', 'Norway', '523658846', 80, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (2, 'Lisha', 'Northfield', 'test2@email.com', 'Central African Republic', '9187880792', 37, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (17, 'Olivette', 'Ivasechko', 'test3@email.com', 'Portugal', '0971359261', 24, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (1, 'Ricardo', 'Pinson', 'test4@email.com', 'Canada', '3369713381', 54, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (3, 'Quill', 'Kundert', 'test5@email.com', 'Russia', '3714676570', 60, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (15, 'Mose', 'Weigh', 'test6@email.com', 'Burkina Faso', '4827370427', 20, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (20, 'Burk', 'Uccelli', 'test7@email.com', 'Afghanistan', '1742849334', 55, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (13, 'Margarette', 'Patkin', 'test8@email.com', 'Indonesia', '0425014096', 68, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values (17, 'Lucine', 'Spraberry', 'test9@email.com', 'Syria', '9092545074', 45, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 2, 'Amelina', 'Burnsyde', 'test10@email.com', 'Spain', '9481310736', 74, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 6, 'Andree', 'Baudts', 'test11@email.com', 'Haiti', '9113366025', 31, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 14, 'Dennison', 'Reide', 'test12@email.com', 'Palestinian Territory', '1620960044', 52, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 12, 'Emmy', 'Burnhill', 'test13@email.com', 'Brazil', '6396446731', 76, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 15, 'Aldrich', 'Simka', 'test14@email.com', 'Poland', '3786012768', 76, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 6, 'Gayleen', 'Yakubov', 'test15@email.com', 'Finland', '0557595002', 62, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 19, 'Sebastiano', 'Fuentes', 'test16@email.com', 'Argentina', '2644446457', 48, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 15, 'Sigmund', 'Lukehurst', 'test17@email.com', 'Portugal', '1959365983', 49, false);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 4, 'Page', 'Lamberteschi', 'test18@email.com', 'China', '4557215610', 37, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 7, 'Stormy', 'Bernadon', 'test19@email.com', 'Venezuela', '2958941477', 40, true);
insert into Reservation (flight_id, name, surname, email, nationality, dni, age, bags) values ( 9, 'Siffre', 'Willwood', 'test20@email.com', 'Philippines', '3274564834', 22, false);
